name: Build CursorLocker2

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v3

      - name: 🛠 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: 📦 Restore NuGet packages
        run: dotnet restore ./CursorLocker2.csproj

      - name: 🏗️ Build CursorLocker2 (без WAP)
        run: dotnet build ./CursorLocker2.csproj --configuration Release --no-restore

      - name: 🚀 Publish CursorLocker2
        run: dotnet publish ./CursorLocker2.csproj --configuration Release --output ./publish --no-restore
      
      #     - name: ⬆️ Upload artifact # ненавижу гитхуй
      #        uses: actions/upload-artifact@v3.1.3
      #        with:
      #          name: CursorLocker2-build
      #          path: ./publish

      - name: 📂 Output files in ./publish
        run: dir ./publish